# To know which targets can be built in your project, Bazel inspects BUILD
# files. They are written in Bazel's build language which is syntactically
# similar to Python. Usually they are just a sequence of declarations of
# rules. Each rule specifies its inputs, outputs, and a way to compute the
# outputs from the inputs.
#
# The rule probably most familiar to people who have used Makefiles before
# (as it is the only rule available there) is the genrule, which specifies
# how the output can be generated by invoking a shell command.

genrule(
  name = "hello",
  outs = ["hello_world.txt"],
  cmd = "echo Hello World 2 > $@",
)